version: '3.8'

#banco + api
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SENHA_ROOT_DB}
      MYSQL_DATABASE: ${BANCO_DB}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${SENHA_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$SENHA_ROOT_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      # AUMENTADO para 120s para garantir que bancos lentos tenham tempo de inicializar do zero
      start_period: 120s

  redis:
    image: redis:7
    container_name: redis_secure
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  #nome("um dns interno") para o docker intentificar os serviços internos do docker
  backend_python:
    #criar a "imagem custon" do back end (o Dockerfile)
    build: .
    container_name: backend_python
    restart: always
    ports:
      - "8080:8080"
    #fala para ele que o .env contem os dados da variaveis de abiente
    env_file:
      - path: .env
        required: false
    #fala para o serviço "db"(banco) e espera para o banco está pronto apra roda a API 
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mysql_data:
  redis_data:

