server {
    listen 80;
    server_name ${BACK_END};

    #Desafio do Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ${BACK_END};

    #Caminhos dos certificados (o Docker vai mapear o nome do domínio aqui)
    ssl_certificate /etc/letsencrypt/live/${BACK_END}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${BACK_END}/privkey.pem;

    #Configurações de segurança padrão
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://backend_python:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}